import React, { useState } from 'react';
import {
  Copy,
  Check,
  CheckCircle2,
  FlaskConical
} from 'lucide-react';
import type { PRDDocument, PrioritizationInitiative, ModuleType } from '../types/finpilot';
import { DEFAULT_PRD } from '../data/fintechScenarios';

interface PrdCopilotProps {
  selectedInitiative?: PrioritizationInitiative | null;
  onNavigateToModule: (m: ModuleType) => void;
}

export const PrdCopilot: React.FC<PrdCopilotProps> = ({
  selectedInitiative,
  onNavigateToModule,
}) => {
  const [prd] = useState<PRDDocument>(DEFAULT_PRD);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'spec' | 'stories' | 'edge_cases' | 'rollout'>('spec');

  const handleCopyMarkdown = () => {
    const md = `# ${prd.title}
**Status:** ${prd.status} | **Version:** ${prd.version} | **Author:** ${prd.author}

## 1. Problem Statement
${prd.problemStatement}

## 2. User Impact
${prd.userImpact}

## 3. Goals
${prd.goals.map(g => `- ${g}`).join('\n')}

## 4. Requirements
${prd.requirements.map(r => `### [${r.priority}] ${r.title}\n${r.description}`).join('\n\n')}

## 5. User Stories (Gherkin Acceptance Criteria)
${prd.userStories.map(u => `### ${u.title}\nAs a ${u.asA}, I want to ${u.iWantTo}, so that ${u.soThat}.\n\n**Criteria:**\n${u.acceptanceCriteria.map(a => `- ${a}`).join('\n')}`).join('\n\n')}

## 6. Edge Cases & Safeguards
${prd.edgeCases.map(e => `- **Scenario:** ${e.scenario}\n  **Expected:** ${e.expectedBehavior}`).join('\n\n')}

## 7. Rollout Plan
${prd.rolloutPlan.map(p => `- **${p.phase}** (${p.duration}): ${p.audience} -> Exit criteria: ${p.exitCriteria}`).join('\n')}
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="p-6 sm:p-8 rounded-3xl bg-[#0b0c12] border border-white/[0.08] relative overflow-hidden shadow-2xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-white/[0.08]">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                PRD Copilot · Production Grade
              </span>
              <span className="text-xs font-mono text-zinc-400">
                {prd.version} · {prd.status}
              </span>
            </div>
            <h1 className="font-syne text-xl sm:text-2xl font-bold text-white tracking-tight">
              {selectedInitiative ? `PRD: ${selectedInitiative.title}` : prd.title}
            </h1>
            <p className="text-xs text-zinc-400 mt-1">
              Generated by FinPilot AI PM Copilot · Targeted for {prd.targetRelease}
            </p>
          </div>

          <div className="flex items-center gap-2 flex-shrink-0">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-white/[0.05] hover:bg-white/[0.09] border border-white/10 text-zinc-200 cursor-pointer transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-cyan-400" />}
              <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={() => onNavigateToModule('experiment')}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-500 text-white cursor-pointer shadow-md shadow-indigo-600/30 transition-all"
            >
              <FlaskConical className="w-3.5 h-3.5" />
              <span>Design Experiment →</span>
            </button>
          </div>
        </div>

        {/* PRD Sub-Tabs */}
        <div className="flex items-center gap-1.5 py-4 border-b border-white/[0.06] overflow-x-auto scroll-x">
          {[
            { id: 'spec', label: '1. Specs & Problem Statement' },
            { id: 'stories', label: '2. User Stories (Gherkin)' },
            { id: 'edge_cases', label: '3. Edge Cases & Safeguards' },
            { id: 'rollout', label: '4. Phased Rollout & KPIs' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap cursor-pointer transition-all ${
                activeTab === tab.id
                  ? 'bg-indigo-500/20 text-white border border-indigo-500/40 shadow-sm'
                  : 'text-zinc-400 hover:text-white'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab Content 1: Specs & Problem */}
        {activeTab === 'spec' && (
          <div className="pt-6 flex flex-col gap-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/[0.06]">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-cyan-400 block mb-1">
                  Problem Statement
                </span>
                <p className="text-xs text-zinc-300 leading-relaxed">
                  {prd.problemStatement}
                </p>
              </div>

              <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/[0.06]">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-rose-400 block mb-1">
                  User & Business Impact
                </span>
                <p className="text-xs text-zinc-300 leading-relaxed">
                  {prd.userImpact}
                </p>
              </div>
            </div>

            {/* Goals & Non-Goals */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-2xl bg-emerald-500/[0.03] border border-emerald-500/20">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-emerald-400 block mb-2">
                  Success Goals
                </span>
                <ul className="flex flex-col gap-1.5 text-xs text-zinc-300">
                  {prd.goals.map((g, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0 mt-0.5" />
                      <span>{g}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="p-4 rounded-2xl bg-zinc-900/60 border border-white/[0.06]">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-zinc-400 block mb-2">
                  Out of Scope (Non-Goals)
                </span>
                <ul className="flex flex-col gap-1.5 text-xs text-zinc-400">
                  {prd.nonGoals.map((ng, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-zinc-600 font-bold">✕</span>
                      <span>{ng}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Functional Requirements */}
            <div>
              <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-cyan-400 block mb-3">
                Functional Specifications
              </span>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {prd.requirements.map((req) => (
                  <div key={req.id} className="p-4 rounded-2xl bg-[#08090d] border border-white/[0.06] flex flex-col justify-between">
                    <div>
                      <div className="flex items-center justify-between mb-1.5">
                        <span className="text-[10px] font-mono text-zinc-500">{req.id}</span>
                        <span className={`text-[9px] font-bold px-2 py-0.5 rounded font-mono ${
                          req.priority === 'P0' ? 'bg-rose-500/20 text-rose-300 border border-rose-500/30' : 'bg-indigo-500/20 text-indigo-300'
                        }`}>
                          {req.priority}
                        </span>
                      </div>
                      <h4 className="text-sm font-bold text-white font-syne mb-1">{req.title}</h4>
                      <p className="text-xs text-zinc-400 leading-relaxed">{req.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Tab Content 2: User Stories (Gherkin) */}
        {activeTab === 'stories' && (
          <div className="pt-6 flex flex-col gap-4">
            {prd.userStories.map((us) => (
              <div key={us.id} className="p-5 rounded-2xl bg-[#08090d] border border-white/[0.08]">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-mono font-bold text-cyan-300">{us.id}: {us.title}</span>
                  <span className="text-[10px] font-mono text-zinc-500">BDD Format</span>
                </div>

                <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04] text-xs text-zinc-300 font-mono mb-3">
                  <span className="text-indigo-400">As a</span> {us.asA}, <br />
                  <span className="text-indigo-400">I want to</span> {us.iWantTo}, <br />
                  <span className="text-indigo-400">So that</span> {us.soThat}.
                </div>

                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-zinc-400 block mb-1.5">
                  Acceptance Criteria (Given / When / Then)
                </span>
                <div className="flex flex-col gap-1 text-xs text-zinc-300 font-mono bg-black/40 p-3 rounded-xl border border-white/[0.04]">
                  {us.acceptanceCriteria.map((ac, idx) => (
                    <p key={idx} className="leading-relaxed">
                      {ac.startsWith('Given') && <strong className="text-emerald-400 font-bold">GIVEN </strong>}
                      {ac.startsWith('When') && <strong className="text-amber-400 font-bold">WHEN </strong>}
                      {ac.startsWith('Then') && <strong className="text-cyan-400 font-bold">THEN </strong>}
                      {ac.startsWith('And') && <strong className="text-indigo-400 font-bold">AND </strong>}
                      {ac.replace(/^(Given|When|Then|And)\s+/, '')}
                    </p>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Tab Content 3: Edge Cases */}
        {activeTab === 'edge_cases' && (
          <div className="pt-6 flex flex-col gap-3">
            {prd.edgeCases.map((ec, idx) => (
              <div key={idx} className="p-4 rounded-2xl bg-[#08090d] border border-white/[0.06] flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div className="sm:w-1/3">
                  <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-amber-400 block mb-1">
                    Edge Scenario #{idx + 1}
                  </span>
                  <p className="text-xs font-semibold text-white">{ec.scenario}</p>
                </div>
                <div className="sm:w-2/3 p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]">
                  <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-cyan-400 block mb-1">
                    System Handling & Fallback
                  </span>
                  <p className="text-xs text-zinc-300 leading-relaxed font-mono">{ec.expectedBehavior}</p>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Tab Content 4: Rollout & KPIs */}
        {activeTab === 'rollout' && (
          <div className="pt-6 flex flex-col gap-6">
            <div>
              <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-cyan-400 block mb-3">
                North Star & Target KPIs
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                {prd.successMetrics.map((m) => (
                  <div key={m.metric} className="p-4 rounded-2xl bg-[#08090d] border border-white/[0.06]">
                    <span className="text-[10px] font-mono text-zinc-400 block mb-1">{m.metric}</span>
                    <div className="flex items-baseline gap-2">
                      <span className="text-xs text-zinc-500 line-through font-mono">{m.current}</span>
                      <span className="text-lg font-black font-mono text-emerald-400">{m.target}</span>
                    </div>
                    <span className="text-[10px] text-zinc-500 font-mono mt-1 block">Window: {m.window}</span>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-indigo-400 block mb-3">
                Phased Rollout Strategy
              </span>
              <div className="flex flex-col gap-2.5">
                {prd.rolloutPlan.map((phase) => (
                  <div key={phase.phase} className="p-3.5 rounded-2xl bg-[#08090d] border border-white/[0.06] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div>
                      <span className="text-xs font-bold text-white font-syne block">{phase.phase}</span>
                      <span className="text-xs text-zinc-400">{phase.audience}</span>
                    </div>
                    <div className="text-right">
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/[0.04] text-cyan-300 border border-white/[0.08]">
                        {phase.duration}
                      </span>
                      <span className="text-[10px] text-zinc-500 block mt-0.5">Exit: {phase.exitCriteria}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
